### ISSUE TITLE
Switching between peers breaks UI

### ISSUE THREAD

**Issue by xla** [radicle-dev/radicle-upstream#1038]
When using the peer selector to switch between peers the UI becomes unusable and all interaction is blocked, console to be investigated.

**Comment by FintanH** [comment]
To help replicate and debug this it's useful if your monorepo state is set up where you have a cloned project from another peer. The error can then be reproduced by switching between a project you have created and the project you cloned or vice versa. You can then refresh to get the working state back again.

As mentioned above, looking at the console you can spot the errors that refer to the `PeerSelector` having undefined properties.

Also to note that this is somewhat related to #1042, since we're switching between our own `PeerId` and remote's `PeerId`.
