### ISSUE TITLE
Update onboarding copy

### ISSUE THREAD

**Issue by juliendonck** [radicle-dev/radicle-upstream#1151]
`This is your handle — it's unique to you! Click to copy it and share with others so that they can find you` 
But we're actually sharing your peerID, and it's unique to your machine. You could have multiple peer ID's in the end when you have multiple machines.

**Comment by abbey-titcomb** [comment]
Wait, I'm confused... We decided that we wanted the peerID to be abstracted to the user as a `handle`. It's what we have in the Glossary. Is this not the case anymore?

**Comment by juliendonck** [comment]
It is the case but as it stands you can't do anything with the `handle`, so showing it in the onboarding is confusing. Either we remove the handle and show nothing, or we tell people that they should remember their `peerID` since it's the only thing they will actually need right now.

**Comment by abbey-titcomb** [comment]
After chatting with @juliendonck and @FintanH about the new Manage Remotes flow, I have some feedback on how we should restructure Onboarding copy to clear up confusion around RadURNs vs. PeerIDs.

As finto explained to me there is a difference between the two user identifiers we call a RadURN and a PeerID. The user's RadURN is what we — in Upstream — describe as the user's *handle* in onboarding (see img1). A project also has a RadURN — which we've _kind of_ been calling a project handle / projectID (see img2 & 3)-. 
 
![image](https://user-images.githubusercontent.com/18275452/98032880-f3006280-1e14-11eb-82ab-1fff25a66a3d.png)

![image](https://user-images.githubusercontent.com/18275452/98032983-1aefc600-1e15-11eb-8964-e230c45342b4.png)

![image](https://user-images.githubusercontent.com/18275452/98033073-3d81df00-1e15-11eb-8753-270faf2c490f.png)

We state that this is how others can search and find you on the Radicle Network. Which *will* be true when we have searching for users built in, but right now we don't. Right now, the only RadURN that is used is the project RadURN when a user wants to find and follow a project on the network (the first step needed to collaborate on a project)

Therefore, I believe showing the user their RadURN as their "handle" in the initial onboarding is confusing for our Beta release because they can't *use* it. Since the PeerID is needed ti add a user as a remote to a project, the way a user will be "discovered" in beta will basically be through their PeerID — which can be found in their Settings, or in the Seed Node UI (seedling.radicle.xyz). I believe we have to make this as clear as possible in Beta to avoid confusion and support any collaboration that is possible in this release.

My proposal to clear up this confusion is as follows:

- [ ]  Update the onboarding copy from:

    _This is your handle — it's unique to you! Click to copy it and share with others so that they can find you._
 
     to:

    _This is your peerID! It's unique to you and this computer. Click to copy it and share with others so they can       collaborate with you. Read more about your peerID._

     (My thought here is we can clear up any discrepancies with the user documentation, and explain the peerID will evolve over time as well has how to use the peerID in the "Manage remotes" flow)

- [ ] Remove user RadURN from below display name. The reasoning here is that if it's present, with an obvious copy-paste symbol, then it will be quite confusing. Either we remove it, and leave the peerID in the settings, or design in a way to copy the peerID from the Profile page _without_ having it replace the position of the user's RadURN. Thoughts @brandonhaslegs @juliendonck ?

- [ ] Highlight the peerID section in the Settings somehow. Maybe we just make it the first section on the Settings page? And update language to remain consistent (i.e. peerID not peerId)

- [ ] Update the search bar in Manage Remotes to say ` Enter a remote's peerID to start collaborating` instead of `remote address`

- [ ] Update seed node UI to explain the difference between what's copied in a Project card (e.g. project RadURN that can be searched) vs. a Peer card (e.g. peerID)

![image](https://user-images.githubusercontent.com/18275452/98033307-9c475880-1e15-11eb-8698-840ae98ce952.png)

- [ ] Officially decide if we want peerID to be called **peerID** in the app, and decide if the project's RadURN should be called **projectID** in the app. The term *handle* can be introduced later, when the user's RadURN can actually be used. 

Please chime in with thoughts & opinions, then we can divide this into separate issues.

**Comment by juliendonck** [comment]
@abbey-titcomb nice work on this. Let's bring this up in the sync today.

**Comment by rudolfs** [comment]
> I believe we have to make this as clear as possible in Beta to avoid confusion and support any collaboration that is possible in this release.

I agree, we should make things as clear as possible, even if it's just for this release and will change later on.
The proposed changes make sense to me, but yeah, let's bring it up during the sync.

**Comment by juliendonck** [comment]
Another thing that came up was the fact that the "password" prompt is also kind of wrong. It seems that talking about an identity is kind of misleading and I also feel this should be about encrypting and decrypting, now it sounds like a web 2.0 identity the way it's described here.

<img width="689" alt="Screenshot 2020-11-05 at 11 19 26" src="https://user-images.githubusercontent.com/2326909/98228479-ef75f400-1f58-11eb-8634-28dab281c55a.png">

**Comment by cloudhead** [comment]
> Another thing that came up was the fact that the "password" prompt is also kind of wrong. It seems that talking about an `account` is kind of misleading and I also feel this should be about encrypting and decrypting, now it sounds like a web 2.0 `account` the way it's described here.

Yes, 100%. The passphrase doesn't protect any account. The only account users have is on Ethereum, and that is managed by an external wallet.

**Comment by abbey-titcomb** [comment]
> > Another thing that came up was the fact that the "password" prompt is also kind of wrong. It seems that talking about an `account` is kind of misleading and I also feel this should be about encrypting and decrypting, now it sounds like a web 2.0 `account` the way it's described here.
> 
> Yes, 100%. The passphrase doesn't protect any account. The only account users have is on Ethereum, and that is managed by an external wallet.

Already being addressed in [#1206](https://github.com/radicle-dev/radicle-upstream/pull/1206#pullrequestreview-526083270)

**Comment by abbey-titcomb** [comment]
Closing this as it was addressed in [#1206](https://github.com/radicle-dev/radicle-upstream/pull/1206#pullrequestreview-526083270)
