### ISSUE TITLE
Give context to all Error notifications

### ISSUE THREAD

**Issue by juliendonck** [radicle-dev/radicle-upstream#1187]
We're expanding the error notification to allow the users to copy the console logs to their clipboard so that they have more information they can share with us when they report a bug. @rudolfs started implementing this for partial projects errors in #1180. 

We have to go through the app and see what context we can give to other `Notification.Error` we have currently.

**Comment by geigerzaehler** [comment]
This involves a couple of things
* Whenever we catch a JS exception in the UI we have to ensure that any additional information that is part of the error is exposed.
* We need to install a handler for [unhandled rejections](https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onunhandledrejection) so we also show errors when we don’t explicitly catch them
* We should also log errors to the console with `console.error` so that devs and dev users can dig more
