### ISSUE TITLE
Fetch on stale gossip

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/radicle-upstream#1242]
At the moment the app considers the tracking of a peer for project successful only if the tracked peer pushes a commit after it has been tracked. The expected behavior is that a peer should be considered tracked after we were able to obtain its refs for the project.

## Background

The state of peer tracking is determined by the `GET /projects/<urn>/peers` endpoint which uses [`coco::State::list_project_peers`](https://github.com/radicle-dev/radicle-upstream/blob/9bc9fe55f7a3b7218f834cf8823e501f0572ddd0/proxy/coco/src/state.rs#L649). We consider a peer as successfully tracked if the `status` field of a peer in the list returned by `list_project_peers` is set to [`Replicated`](https://github.com/radicle-dev/radicle-upstream/blob/9bc9fe55f7a3b7218f834cf8823e501f0572ddd0/proxy/coco/src/project/peer.rs#L177). This is the case if the following ref exists in the monorepo:

    refs/namespaces/<project_id>/refs/remotes/<peer_id>/self

This check is implemented [here](https://github.com/radicle-dev/radicle-upstream/blob/9bc9fe55f7a3b7218f834cf8823e501f0572ddd0/proxy/coco/src/state.rs#L618-L619).

## Solution

To achieve the expected behavior the local peer should try to obtain the refs given above after tracking the remote peer.

The right way for this seems to emit a `Want` for the project URN with the tracked peer ID as the [`origin`](https://github.com/radicle-dev/radicle-link/blob/e5e1a1b3a251ae9f37dcb2c3211efcc186ea2503/librad/src/net/peer/types.rs#L108). However, at the moment, `librad` [does not apply](https://github.com/radicle-dev/radicle-link/blob/e5e1a1b3a251ae9f37dcb2c3211efcc186ea2503/librad/src/net/peer.rs#L590-L592) the corresponding have requests if the `rev` field is `None`.

**Comment by geigerzaehler** [comment]
This problem causes issues in the tracking interaction. Assume two peers are replicating a project and are online. I tell the app to follow the project. The proxy we’ll receive an anoucement of the commit for the master branch from one of the peers. The proxy (or more specifically `librad`) will determine that it is interested in the project and fetch the project repo from the peer using [`fetch_repo`](https://github.com/radicle-dev/radicle-link/blob/28b40af84a6455efb9167faf8c20aa3f05a48c29/librad/src/git/storage.rs#L725). Along with the commits of the master branch, `fetch_repo` will also fetch the peers refs for the project in the monorepo and will add these refs as remotes to the project namespace in the monorepo. This finalizes the tracking operation of a peer for the project and the app will show it in the “following” state.

Now, if we add the other peer to the project’s remotes this action will never be acknowledged. This means that we’ll see the “these remotes haven’t been found yet” message for the other peer forever. The reason is that the commit shas in the anouncements of branch heads from the second peer will match the commit shas from the the first peer and will this be considered stale. Consequently we never call `fetch_repo` and will never add the second peer to the list of remotes in the monorepo.

The first solution to address this is a workaround leveraging existing protocol functionality without making changes. In the proxy, whenever we see an anouncement from a peer for a repository branch head and we’re tracking the corresponding project and we don’t have the remote information we will call `fetch_repo` even if the information is considered stale.

**Comment by geigerzaehler** [comment]
Turns out, much of what I wrote in my comment was incorrect. I’ve updated the description with the current state of the investigation.
