### ISSUE TITLE
Long error messages are not readable

### ISSUE THREAD

**Issue by MeBrei** [radicle-dev/radicle-upstream#1266]
<img width="1440" alt="Screenshot 2020-11-17 at 13 47 44" src="https://user-images.githubusercontent.com/16262137/99392108-79b84380-28db-11eb-83e3-98c636afdf83.png">

If the message of an error is too long, parts of the notification are outside of the view and the `Copy error` button is not visible. It is not possible to vertical scroll the error message.

**Comment by NunoAlexandre** [comment]
FYI, on my https://github.com/radicle-dev/radicle-upstream/pull/975 branch, I have made long-enough notifications scrollable for my developer sake for the rare cases where these monstrosities take place. You can have a look there, shall that be useful to you.

**Comment by brandonhaslegs** [comment]
Give all notifications a max width so that the notification never extends over the sidebar. Truncate the message but make sure the actions are always visible on the notification.

Something like this:

![image](https://user-images.githubusercontent.com/4406983/99394311-f7ca1980-28de-11eb-98fa-9e4b69ea0c28.png)
