### ISSUE TITLE
Relative links in rendered markdown interact with UI

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#1347]
Refs https://github.com/radicle-dev/radicle-upstream/issues/1335.

When clicking on relative links in rendered markdown they lead to the profile page.
Clicking on a relative link in rendered markdown should have no effect in the UI for now.

Steps to repro:

1. `git clone https://github.com/BurntSushi/ripgrep.git`
2. In the UI navigate to the project `ripgrep`
3. In the rendered `README.md` click on the "Installation" link

**Comment by MeBrei** [comment]
Actually making relative links work would require some refactoring in the source browsing code, since navigating to a file is not done via changing the url currently.

I did not find a way to disable relative links via `marked` directly. We could match relative `href`s via css and disable any pointer events, but we would have to make sure we catch all variants and a disabled link that I can see with dev tools might be a bit frustrating.
