### ISSUE TITLE
Take inventory of proxy TODOs

### ISSUE THREAD

**Issue by xla** [radicle-dev/radicle-upstream#137]
Over the last season a lot of TODOs accumulated in the proxy codebase. Let's take inventory and see if they are still relevant and if there are ways to address them.

**Comment by garbados** [comment]
A quick grep of the proxy src reveals:

`src/schema/registry.rs:    // TODO(xla): Use String32 type.`
`src/schema/registry.rs:    // TODO(xla): Use String32 type.`

I can close these out.

`src/schema/registry.rs:            // TODO(garbados): unpanic`

How should we handle a CBOR serialization failure? This `.expect` exists because
I'm not sure how we want to handle failure.

`src/schema/registry.rs:        // TODO: remove .expect() call, see: https://github.com/radicle-dev/radicle-registry/issues/185`

The linked issue has been closed out so this should can be resolved now.

`src/schema/error.rs:            // TODO(garbados): expand via sub-match`
`src/schema/error.rs:            // TODO(garbados): expand via sub-match`

These TODOs pertain to Radicle runtime and protocol errors, which are currently
not fully enumerated. It stands to question whether we want to handle these in
further detail, in which case I can expand them. Otherwise I'll just remove the
TODOs.

`src/schema/registry.rs:    // TODO(xla): Use actual transaction hash type.`
`src/schema/registry.rs:        // TODO(xla): Unpack the result to find out if the application of the transaction failed.`
`src/schema/mod.rs:        // TODO(xla): Get keypair from persistent storage.`
`src/schema/mod.rs:        // TODO(xla): Remove single-threaded executor once async/await lands in juniper:`
`src/schema/mod.rs:        // TODO(xla): Ressurect once we have figure out the project listing strategy.`
`src/main.rs:// TODO(xla): Handle all Results properly and never panic outside of main.`
`src/main.rs:// TODO(xla): Remove exception for or_fun_call lint.`
`src/main.rs:// TODO(xla): Remove let_underscore_must_use once the issue is resolved: https://github.com/rust-lang/rust-clippy/issues/4980`

These are all marked for @xla so I'll leave them for your consideration.

**Comment by xla** [comment]
@garbados Thanks for the inventory. The name in the parans is not an assignment, but signals authorship to have a chance to obtain more context if neceesayr. :3

**Comment by xla** [comment]
> A quick grep of the proxy src reveals:
> 
> `src/schema/registry.rs: // TODO(xla): Use String32 type.`
> `src/schema/registry.rs: // TODO(xla): Use String32 type.`
> 
> I can close these out.

Already addressed in #134

> `src/schema/registry.rs: // TODO(garbados): unpanic`
> 
> How should we handle a CBOR serialization failure? This `.expect` exists because
> I'm not sure how we want to handle failure.

It would be nice to take the time and go through the scenarios where this can fail and what the resulting user experience will be. From that we should be able to devise the right plan.

> `src/schema/registry.rs: // TODO: remove .expect() call, see: https://github.com/radicle-dev/radicle-registry/issues/185`
> 
> The linked issue has been closed out so this should can be resolved now.

As long as the actual `expect` is gone afterwards.

> `src/schema/error.rs: // TODO(garbados): expand via sub-match`
> `src/schema/error.rs: // TODO(garbados): expand via sub-match`
> 
> These TODOs pertain to Radicle runtime and protocol errors, which are currently
> not fully enumerated. It stands to question whether we want to handle these in
> further detail, in which case I can expand them. Otherwise I'll just remove the
> TODOs.

Could you outline pros and cons for either?

> `src/schema/registry.rs: // TODO(xla): Use actual transaction hash type.`
> `src/schema/registry.rs: // TODO(xla): Unpack the result to find out if the application of the transaction failed.`
> `src/schema/mod.rs: // TODO(xla): Get keypair from persistent storage.`
> `src/schema/mod.rs: // TODO(xla): Remove single-threaded executor once async/await lands in juniper:`
> `src/schema/mod.rs: // TODO(xla): Ressurect once we have figure out the project listing strategy.`
> `src/main.rs:// TODO(xla): Handle all Results properly and never panic outside of main.`
> `src/main.rs:// TODO(xla): Remove exception for or_fun_call lint.`
> `src/main.rs:// TODO(xla): Remove let_underscore_must_use once the issue is resolved: https://github.com/rust-lang/rust-clippy/issues/4980`
> 
> These are all marked for @xla so I'll leave them for your consideration.

See https://github.com/radicle-dev/radicle-upstream/issues/137#issuecomment-584873478

**Comment by garbados** [comment]
> The name in the parans is not an assignment, but signals authorship

Ah, noted. That makes sense.

> Could you outline pros and cons for either?

It depends to what degree such failures are actionable. Protocol errors include issues like a failure to decode messages from the registry, which is out of the user's hands. Dispatch errors include network and lookup failures, which can be raised to the user's attention by way of, "Are you connected to the internet?"

At worst, enumerating these errors means confused users will have detailed error information to file in support requests. At best it will give them precise and actionable information, like "I can't do that while offline. Please try again later."

> `src/schema/mod.rs: // TODO(xla): Get keypair from persistent storage.`

Do you have recommendations for handling persistent storage? I have been wondering how to approach this.

**Comment by xla** [comment]
> Do you have recommendations for handling persistent storage? I have been wondering how to approach this.

@garbados Conveniently the CoCo team just made the keystorage reusable in radicle-dev/radicle-link#47 - this would where I'd look first and start see how to use that component for our needs.

**Comment by xla** [comment]
> It depends to what degree such failures are actionable. Protocol errors include issues like a failure to decode messages from the registry, which is out of the user's hands. Dispatch errors include network and lookup failures, which can be raised to the user's attention by way of, "Are you connected to the internet?"
> 
> At worst, enumerating these errors means confused users will have detailed error information to file in support requests. At best it will give them precise and actionable information, like "I can't do that while offline. Please try again later."

@garbados Can we distill this into descriptive behavior and how errors enabling that would look like?

**Comment by garbados** [comment]
Sorry for the reply delay.

> Can we distill this into descriptive behavior and how errors enabling that would look like?

I'm not sure I understand what you mean. Could you explain in more detail?

**Comment by xla** [comment]
@garbados Sure thing

What I mean is actually start describing what we want to surface in what way to the user. As a vivid example is the connectivity message you wrote up above. So start describing which error could result in what actionable UX and what is just informative and what shouldn't be surfaced at all and we need better handling under the hood.

**Comment by xla** [comment]
Stale.
