### ISSUE TITLE
Border radius glitch when hovering over projects in the "Still looking…" section on the Following tab of your profile 

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#1447]
![image](https://user-images.githubusercontent.com/4406983/100988083-96957d80-354f-11eb-9340-2f2f646d670d.png)

if you don't see it, it's happening on the corners. some inner element is probably not rounded 
![image](https://user-images.githubusercontent.com/4406983/100990224-f1c86f80-3551-11eb-8ce3-e5c17c8b2e83.png)

**Comment by xla** [comment]
Nice spot. I see this solved with manually adding border radiuses to children. This is brittle as component hierarchies can easily change and then those changes would get lost. Why aren't we adopting the strategy of using `overflow` for this so that the borders of the parent apply regardless of the children.
