### ISSUE TITLE
Button "Reach out to support" redirects to a broken link

### ISSUE THREAD

**Issue by pimato** [radicle-dev/radicle-upstream#1483]
Hey guys, 

just tried to get radicle working on macOS and while getting errors I tried to use the `Reach out to support` button which redirected me to https://matrix.to/#/%23support:radicle.community , which is a page to create sharable links. Looks like the link is broken:

<img width="577" alt="Bildschirmfoto 2020-12-10 um 12 20 26" src="https://user-images.githubusercontent.com/5337809/101765785-1ab4ab80-3ae2-11eb-8cfd-8acd5d03b140.png">

**Comment by xla** [comment]
Thanks for reporting the issue, we are looking to find out why it broke.

**Comment by xla** [comment]
It looks to break because the second hash dertermining the channel is encoded.

**Comment by abbey-titcomb** [comment]
@pimato — this should be the correct link: https://matrix.to/#/#support:radicle.community.

Let me know if it works. We'll work on fixing this in the app.

**Comment by rudolfs** [comment]
To clarify: I think this only happens on the _Blue Screen of Death_ page.

![bsod](https://user-images.githubusercontent.com/158411/101911572-d51ae000-3bc0-11eb-839a-ba0e8efacb63.gif)

This is probably because we're using a button for the external link instead of an `<a>` tag.
https://github.com/radicle-dev/radicle-upstream/blob/master/ui/Screen/Bsod.svelte#L30

**Comment by abbey-titcomb** [comment]
@rudolfs — any idea how to fix?

**Comment by juliendonck** [comment]
Closed by https://github.com/radicle-dev/radicle-upstream/pull/1511
