### ISSUE TITLE
Clicking on sidebar peer icon does nothing

### ISSUE THREAD

**Issue by laanwj** [radicle-dev/radicle-upstream#1514]
Clicking on this icon does nothing, I am not sure it's supposed to:

![screenshot](https://user-images.githubusercontent.com/126646/104119825-aa908400-5332-11eb-916f-272e5af46bdd.png)

I think I'd personally expect it to show a list of peers, or some kind of statistics screen.

**Comment by juliendonck** [comment]
Hey @laanwj, thank you for opening the issue. 
I'm glad you have that expectation because we'd like to do exactly that. As we believe it would be a great discovery feature, but at the moment we feel that that need is alleviated by the [seed node UI ](seedling.radicle.xyz). 
We are currently focusing our effort on what we feel are more high impact features, but we've put it in the backlog and will hopefully get to it soon.
