### ISSUE TITLE
Upgrade vulnerable yargs-parser dependency

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#1533]
https://github.com/radicle-dev/radicle-upstream/security/dependabot/yarn.lock/yargs-parser/open

**Comment by geigerzaehler** [comment]
The offender is the following list of dependencies

radicle-contracts -> @ensdomains/ens -> solc -> yargs -> yargs-parser

All other instance of the `yargs-parser` package in our project use a fixed version. Since the `solc` dependency of `@ensdomains/ens` is never explicitly used in our project (in particular, not in production) I’d suggest to close this.

**Comment by rudolfs** [comment]
If we close this issue, is there a way to suppress this warning?

<img width="918" alt="Screenshot 2021-01-22 at 11 14 47" src="https://user-images.githubusercontent.com/158411/105478128-1368ec00-5ca3-11eb-92b9-d3b2a227a59b.png">

We also get the warning every time we push to GitHub.

**Comment by geigerzaehler** [comment]
There’s a “dismiss” button on the page you linked that provides an option “vulnerable code is not actually used”. I’ll click that.

**Comment by geigerzaehler** [comment]
I’ve closed the security issue.
