### ISSUE TITLE
Project view should be reactive to git updates to the repo

### ISSUE THREAD

**Issue by juliendonck** [radicle-dev/radicle-upstream#1597]
When you're looking at your project or at someone else's remote and there's an update through `git rad push` the UI should update.

**Comment by NunoAlexandre** [comment]
I have been looking at this issue and as I was suspected, there' some learning curve required to tackle this.

I see in `ui > Screen > Project.svelte` that we listen to project events for the local peer and `refresh()` the project view screen when such an event occurs. 

``` typescript
  localPeer.projectEvents.subscribe(event => {
    if (!event) {
      return;
    }

    if (event.urn === urn) {
      refresh();
    }
  });
```

Looking at `localPeer.projectEvents` and into how these events are fetched from `proxy`, I don't _see_ how we could make this reactive by design, i.e., without a recurring polling mechanism coming from the UI.

Moreover, these events are only `localPeer` events, while this issue aims to also tackle the case when we are looking at a project under someone else's remote.

What I _also_ want to avoid is having the Project view re-rendering at every project event that does not affect the direct page being viewed. For example, if I am looking at a specific commit diff and a new commit is added, I don't want a "refresh" flicker to occur. Hopefully, that will be no issue and it's handled for free by Svelte or it's just a matter of us filtering the right events given the current location we are in.

@xla could you perhaps provide some pointers or suggestions on how we should go about this?

**Comment by xla** [comment]
What `refresh` does is to kick off a fetch of the peer list, this is to ensure that if the local peer gets notice of a remote peer tracking/forking or contributing to the project the list is up-to-date and reflects the known remotes. So one can think of this as an event system with lightweight notifications which trigger data fetch operations. The mechanism can be applied to update other data sources like commits. The part that needs to be filled out is what series of events in the proxy would trigger a `ProjectUpdated` when a push to the monorepo is completed:

https://github.com/radicle-dev/radicle-upstream/blob/15f1293950331a16cc2de32655c02a041349b8bf/proxy/api/src/notification.rs#L71-L76

> Moreover, these events are only `localPeer` events, while this issue aims to also tackle the case when we are looking at a project under someone else's remote.

In this context `localPeer` is just a namespace to make clear it's peer operated by the local proxy and will not influence the scope of which screen is viewed by the user in the ui.

> What I _also_ want to avoid is having the Project view re-rendering at every project event that does not affect the direct page being viewed. For example, if I am looking at a specific commit diff and a new commit is added, I don't want a "refresh" flicker to occur. Hopefully, that will be no issue and it's handled for free by Svelte or it's just a matter of us filtering the right events given the current location we are in.

With Svelte's reactivity in mind updating the stores that back the view data will be non-invasive as long as rendered lists are properly keyed.
