### ISSUE TITLE
Tests leak resources due to `into_running()`

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-upstream#1648]
The proxy tests commonly use
~~~rust
tokio::task::spawn(peer.into_running())
~~~
in conjunction with a temporary directory that the peer reads and writes.

Since we don’t store the task handle and abort it, the peer will run as long as the tokio executor is running. This leaks resources and might interfer with the rest of the environment. One particular issue is that the temporary directory created by `tempfile::tempdir()` is dropped and the peer still tries to write to it which leads to errors and potentially failing tests.

To address this issue we need to rethink the following pattern
~~~rust
let coco_peer = coco::bootstrap(/* uses tmpdir */).await?;
let peer = coco_peer.peer.clone();
let peer_control = coco_peer.control();
tokio::spawn(coco_peer.into_running());
return (peer_control, peer)
~~~
The goal would be to return a handle that stops the peer when it is dropped.

**Comment by FintanH** [comment]
I like the approach in `radicle-link` where there are structs for tests that hold the resources, for example, [BoundTestPeer](https://github.com/radicle-dev/radicle-link/blob/master/librad-test/src/rad/testnet.rs#L38-L43). We could do something similar where we hold the spawned handle in a struct along with the `peer` and `peer_control`.

**Comment by kim** [comment]
You may also want to take a look at [this](https://github.com/radicle-dev/radicle-link/blob/a8f79e4b557030c07e64f7cfb299c000c754c751/seed/src/lib.rs#L183-L201).

As per tincan phone technology, the run loop is independent of the handle to talk to it. This means that it is advisable to have some basic supervision in order to either restart it, or abort the process once an `Endpoint::Down` event is received.
