### ISSUE TITLE
Migrating a project with existing remote failed.

### ISSUE THREAD

**Issue by viraptor** [radicle-dev/radicle-upstream#1846]
I attempted to import a project under a new 0.2.3 profile. The app told me: 
```
{
  "code": "ProjectCreationFailure",
  "source": {
    "code": "UnknownException",
    "details": {
      "name": "Error",
      "body": {
        "message": "the `rad` remote was found but the url field does not match the provided url, found: 'rad://hnrkk458xbhmjopnxs7ezpoprip7tc6nr414o.git' expected: 'rad://hnrkpwtfi19i3gzjiqq7higumgf4z6r6xkr8o.git'",
        "variant": "URL_MISMATCH"
      },
      "response": {}
    }
  }
}
```

The remotes afterwards are:

```
rad     rad://hnrkk458xbhmjopnxs7ezpoprip7tc6nr414o.git (fetch)
rad     rad://hnrkk458xbhmjopnxs7ezpoprip7tc6nr414o.git (push)
rad_old rad://hyyb6uybt1npzqinex1b133rmqjxaeswzk8ufb6jrinrifjzq5bj6o@hwd1yrebttx7x8qrif5bctn33px956uu913bsxt57yhyiez56y6o5r7zddo.git (fetch)
rad_old rad://hyyb6uybt1npzqinex1b133rmqjxaeswzk8ufb6jrinrifjzq5bj6o@hwd1yrebttx7x8qrif5bctn33px956uu913bsxt57yhyiez56y6o5r7zddo.git (push)
```

The error reoccurs if I retry the import.

After I renamed `rad` to `rad_test` and retried, the import succeeded.

**Comment by FintanH** [comment]
So this means that you created a project that leads to a different Urn than the existing working copy. This can be due to changing the name or the description. Since Radicle shouldn't be opinionated on what happens here, it's left up to the user to resolve this. So the two options are:
1. Give the same details for project creation to lead to the same Urn
2. Rename the `rad` remote -- to preserve those remote branches if needs be -- and run the creation again

Hope that helps @viraptor :blush:
