### ISSUE TITLE
Update "reach out for support" to a more general link

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#1892]
This button links to the Matrix server Support channel, which is kind of okay, but since we now have a Discord with a support channel there, maybe we could link this to maybe radicle.community which lists all possibilities for support?

![image](https://user-images.githubusercontent.com/4406983/118500163-db8d2500-b727-11eb-8e46-3c64158cd5b1.png)

**Comment by rudolfs** [comment]
[This](https://github.com/radicle-dev/radicle-upstream/blob/main/ui/App/UnrecoverableErrorScreen.svelte#L42) should be updated to link to the [#upstream channel on discord](https://discord.com/channels/841318878125490186/843873418205331506).

**Comment by brandonhaslegs** [comment]
@rudolfs I thought we should link to https://radicle.xyz/community maybe, since all ways to reach out are listed there?

**Comment by rudolfs** [comment]
Good point, wasn't aware of https://radicle.xyz/community.

I just aligned it with the other link that we have in the Settings screen, which also links to #upstream in discord directly. My thinking was that since we'll soon reach out to our first official testers, it might make sense to point them to where we hang out, so we can react more quickly.

I'm personally not monitoring any other channels besides #upstream.

What do you think @Kaihuang724?

**Comment by brandonhaslegs** [comment]
Well, lots of the channels (including #Support) are bridged to Matrix. So you are also _kinda_ on Matrix.

**Comment by rudolfs** [comment]
> Well, lots of the channels (including #Support) are bridged to Matrix. So you are also kinda on Matrix.

I have notifications on _only_ for #upstream. 👹

**Comment by Kaihuang724** [comment]
I think we should go with Discord. Looking at this https://radicle.xyz/community, there's quite a few links and mental jumps I have to make as a user to figure out where I should notify the Radicle team about any issues. Since they've already encountered the error and are likely frustrated, we should provide the more direct path for them to message us.
