### ISSUE TITLE
👋 Share your device ID for contributions with Radicle Upstream

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-upstream#1958]
If you want to submit contributions through Radicle Upstream itself you can post your device ID here so that we can track you. To submit a patch, follow [these instructions](https://github.com/radicle-dev/radicle-upstream/blob/main/docs/submit-patch-using-upstream.md).

Upstream Project ID: `rad:git:hnrk8ueib11sen1g9n1xbt71qdns9n4gipw1o`
Hosted on: [https://maple.radicle.garden](https://app.radicle.network/seeds/maple.radicle.garden/rad:git:hnrk8ueib11sen1g9n1xbt71qdns9n4gipw1o/tree/a90bd1248614c0876ad7ff43b5516a42186366e9)

**Comment by Jayman2000** [comment]
`hyy4aj3wiqq1o6m5un17sq4m74i4btx8w4ypryri91nrauz9odhfis`

**Comment by rudolfs** [comment]
Thanks @Jayman2000! Merged in via https://github.com/radicle-dev/radicle-upstream/commit/52acf5f61d1e1014f85d23a7e9a731c7845e8026 and https://github.com/radicle-dev/radicle-upstream/commit/40f5d81aed568a6c9025126fd0bd587207fd8da9.

**Comment by gsaslis** [comment]
Hey there! 👋🏼 

`hyd5xybasxyicg3ap4izs8jyg1u4ardy95xaddd6yu4mzqb1oqtiye`

**Comment by rudolfs** [comment]
Hey @gsaslis!

It's your Device ID, that's how we can find your contributions to a project.

<img width="1440" alt="Screenshot 2022-01-10 at 10 44 25" src="https://user-images.githubusercontent.com/158411/148745521-fe7864a6-843c-4203-a941-0e0c02ab7116.png">

Did you submit a patch already? So far I can't find anything under that Device ID on our seed.

**Comment by gsaslis** [comment]
> It's your Device ID, that's how we can find your contributions to a project.

@rudolfs yes :) what I meant was that my previous message itself (not just the Device ID)  is kind of a "track request", in the sense that I am asking you to track me before I can contribute. :)  I found it kind of interesting that the "track request" term - if not already coined - might be to radicle what pull requests first were when GitHub came out: a unique term that succinctly expresses a large part of the contribution flow ;) 

> Did you submit a patch already? So far I can't find anything under that Device ID on our seed.

No, I haven't submitted a patch yet. I thought sharing the device id was a prerequisite step. I wanted to try out submitting patches through upstream rather than submitting a PR here. I'll ask in discord if i need some help, if that's ok ;)

**Comment by rudolfs** [comment]
> @rudolfs yes :) what I meant was that my previous message itself (not just the Device ID) is kind of a "track request", in the sense that I am asking you to track me before I can contribute. :) I found it kind of interesting that the "track request" term - if not already coined - might be to radicle what pull requests first were when GitHub came out: a unique term that succinctly expresses a large part of the contribution flow ;)

You can already contribute before anyone is tracking you, your changes will land on the seed in any case. It's just so that I can find them, I also have to add your Device ID to my client. But yeah, it has some similarities with a pull request, I guess.

> No, I haven't submitted a patch yet. I thought sharing the device id was a prerequisite step. I wanted to try out submitting patches through upstream rather than submitting a PR here. I'll ask in discord if i need some help, if that's ok ;)

Gotcha. The intention with this pinned issue was that people post their Device IDs once the contribution is up already. Maybe we should clarify that in the description. 🤔

**Comment by gsaslis** [comment]
> It's just so that I can find them, I also have to add your Device ID to my client. 

Exactly, yes! And if I tell you "please add my device ID to your client", this is what sounded like a "Track Request" to me. :)  Anyway... was just a random thought. 😅 

> Maybe we should clarify that in the description

well, _I_ may have been confused, but if this is the first time this is happening, perhaps it's not worth bothering... ;)

**Comment by rudolfs** [comment]
Can we close this @geigerzaehler ?
