### ISSUE TITLE
Rename `master` to `main` in the upstream repo

### ISSUE THREAD

**Issue by juliendonck** [radicle-dev/radicle-upstream#2039]
@geigerzaehler @rudolfs Would it be hard for us to rename our default branch?

**Comment by rudolfs** [comment]
Here's all the things that we'd need to change, that I can think of:
- [ ] [CI macos environment](https://github.com/radicle-dev/infra/blob/master/ci/macos/usr/local/etc/buildkite-agent/hooks/environment#L16).
- [ ] CI build scripts
- [ ] release docs
- [ ] specs and the associated `radicle-platinum` repository

I think from these the `radicle-platinum` change will be the most hairy one, because other repos besides upstream also depend on it.

**Comment by geigerzaehler** [comment]
> I think from these the `radicle-platinum` change will be the most hairy one, because other repos besides upstream also depend on it. Then again, maybe the specs are not related to changing this repository's default branch? shrug

As far as I know it should be possible to change the default branch of this repo without changing the default branch of `radicle-platinum`.

**Comment by juliendonck** [comment]
related to #1058

**Comment by geigerzaehler** [comment]
Beyond code changes, we need to
- [ ] Change the default branch in the Github repo settings
- [ ] Change the matching pattern for the branch protection rules in the Github repo settings
