### ISSUE TITLE
Use button component for add org button in sidebar

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#2073]
<img width="49" alt="image" src="https://user-images.githubusercontent.com/4406983/123279131-dcc02780-d507-11eb-9a5a-c796a2d90cb1.png">

This is currently just an SVG. it should use the outline icon button component, and the `plus` icon.

**Comment by nishit-prasad** [comment]
Hello! I am new to open source and would like to work on this. Please advise.

Currently, I am reviewing the docs/guidelines.

**Comment by juliendonck** [comment]
> Hello! I am new to open source and would like to work on this. Can I take this up?
> 
> Currently, I am reviewing the docs/guidelines.

Sure, let us know where you need help

**Comment by nishit-prasad** [comment]
Sure. Thank you! I am currently setting it up. Can it be assigned to me?

**Comment by nishit-prasad** [comment]
@brandonhaslegs 

I was able to setup the environment but I am not seeing Add Org icon on the sidebar.
(I believe it should be right below the avatar icon on the left sidebar)

Did I missing anything during my build process?

![Screen Shot 2021-06-30 at 4 24 34 PM](https://user-images.githubusercontent.com/64563418/123949144-de826300-d9bf-11eb-93b5-da3c6b41543e.png)

**Comment by brandonhaslegs** [comment]
Are you building the latest master? When I pull the latest master, I do see the button. 🤔

<img width="496" alt="image" src="https://user-images.githubusercontent.com/4406983/123953369-6f007980-d9a7-11eb-8df7-e95bfa66f2a5.png">

**Comment by rudolfs** [comment]
> I was able to setup the environment but I am not seeing Add Org icon on the sidebar.

You have to first connect your wallet to see the orgs features.

**Comment by nishit-prasad** [comment]
I did build off master track. Let me try by adding my wallet. Will let you know. Thank you!

**Comment by nishit-prasad** [comment]
@brandonhaslegs @rudolfs 
Thank you for the help. I was able to see the missing icon (button).

I was also able to find the right code where to fix this issue.

But before making the necessary changes, I have the following questions such that the changes do not conflict with required design and consistencies:

![ScreenRecord](https://user-images.githubusercontent.com/64563418/124126487-558b2a80-da98-11eb-8aed-26eaf523f0c6.gif)

If you refer the above gif:
1. On the sidebar, I see the `indicator` when I hover amongst all other sidebar items except the add-org button. I can do the same for this button by inserting the `indicator` property [here](https://github.com/radicle-dev/radicle-upstream/blob/master/ui/DesignSystem/Sidebar/OrgList.svelte#L74) such that it's consistent. Shall I include that? 
2. When I add an outline Button component with Icon.Plus svg - I see the increase in width. I can play around with the right padding but since it could be a hardcoded-value, do you have any recommendations?
3. The Icon.Plus svg holds the blue hover color (`rgba(85, 85, 255, 1)`). So, when you hover:
- Currently, the + icon and the surrounding outline are covered with this color. Do you expect the same for the button wrapped around it? (because other sidebar items don't have this color when you hover)
- The Button component has a default hover style (goes a little darker gray - just like in the case for [New Project] button). Would you like to disable this or leave the default?

The reason I am asking these is because if I compare with other sidebar items, there are no hover color changes (and a missing **indicator** property). And _if_ we are to maintain consistency, then the simplest fix would be to just return `<Icon.Plus />` in `AddOrgButton.svelte` file (or wrap Button component around it with no styles) and remove everything else. In other words:
Other sidebar items are defined like (example) in [Sidebar.svelte](https://github.com/radicle-dev/radicle-upstream/blob/master/ui/DesignSystem/Sidebar.svelte#L74):
```
<SidebarItem>
...
   <Icon.MagnifyingGlass />
...
</SidebarItem>
```
but for Org, in sidebar it is:
```
<OrgList />
```
which in turn has:
```
...
<SideBarItem>
   <AddOrgButton />
</SideBarItem>
...
```

**Comment by brandonhaslegs** [comment]
Hey thanks for looking into this!

1. No indicator please

And I agree with you, good idea. Let's just use the icon, just like the rest of the icons in the sidebar. So no button component needed. Make sure to add the `button-transition-big` class to the icon, which adds a transition when clicked.

**Comment by nishit-prasad** [comment]
Awesome. Thank you! I look forward to the final decision on the indicator.

**Comment by juliendonck** [comment]
Yes, if we're removing the outline we should add the indicator. Nice write up :)

**Comment by nishit-prasad** [comment]
Thank you. Appreciate it!

So to sum up, I will do the following changes (please comment otherwise):
- [ ] Replace the hardcoded `<svg>` inside `<AddOrgButton />` component with `<Icon.Plus />` (Removing all the styles in that file - as they are inherited just like the way for other sidebar items)
- [ ] Add `indicator` in the `<SideBarItem />` in `<OrgList />` component.

**Comment by nishit-prasad** [comment]
PR is up and ready! 😄
