### ISSUE TITLE
Differentiate pending anchored projects with more than just icon color

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#2078]
When a user signs an anchor transaction but doesn't execute the transaction yet, the project appears to show up as if it was already anchored. We should make this more clear that it is in fact still pending.

**Comment by brandonhaslegs** [comment]
Actually, what happened to this design? Maybe this is enough?
![image](https://user-images.githubusercontent.com/4406983/123641762-e6f16700-d822-11eb-9916-33f7501fecaa.png)

**Comment by rudolfs** [comment]
> Actually, what happened to this design? Maybe this is enough?

The problem was that we have 4 kinds of anchored projects:
  - Pending anchor with no p2p data
  - Pending anchor with p2p data
  - Confirmed anchor with no p2p data
  - Confirmed anchor with p2p data

To avoid having to build representations for each of these cases I opted to just differentiate them via the icon color and pop-over content.
