### ISSUE TITLE
Changed code signature in MacOS v 2.0.12?

### ISSUE THREAD

**Issue by suschizu** [radicle-dev/radicle-upstream#2656]
Hello - I've received a warning that the code signature changed between version 2.0.11 and 2.0.12

EXPECTED Monadic GmbH (35C27H9VL2) but FOUND Rudolfs Osins (9X5CAG43DL)

Can you confirm this? Thanks

**Comment by rudolfs** [comment]
Yes, I can confirm that this is expected.
Monadic is being wound down as we transition to a more decentralised way of working.


For context, here's a snipped of the discussion we had:
<img width="707" alt="Screenshot 2021-12-03 at 17 24 07" src="https://user-images.githubusercontent.com/158411/144637103-befd3e17-a17a-4ccd-8f04-49f5d98ef03e.png">

Maybe @cloudhead and @lftherios can add a seal of approval here, so that it's more official?

**Comment by rudolfs** [comment]
> Hello - I've received a warning that the code signature changed between version 2.0.11 and 2.0.12

Curious to where you got this warning? Could you provide a screenshot?

**Comment by suschizu** [comment]
great thanks for the fast answer! I'm running security checks for an app called MacUpdater - that also contain checking if a code signature changes between versions (so this could be a sign that it's perhaps a corrupted version or else) - I just use the common  'codesign -dv --verbose <path>'  - it's just an intern script - nothing official :)
