### ISSUE TITLE
Maintainer doesn't pull its own updates from an Upstream seed

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#2704]
As a maintainer of a project I had published a project on a seed node and subsequently lost the data locally, but retained the identity. When I tried to follow my own project from the seed node I got the following error:

```
{
  "79a2a194ac8148df149e18f64e18adf168d56d25": {
    "state": "Found",
    "peers": {
      "hydyq6xmgp3amt44z41n6cbods1osx73j5z6fky5xx4yx33afycyfc": {
        "failed": {
          "reason": " ⮩ identity not found"
        }
      }
    }
  }
}

  2022-01-03T13:05:48.347778Z  WARN radicle_daemon::peer::run_state: cloning failed, reason: Replication(Replicate(Replication(MissingIdentity)))
    at /Users/rudolfs/.cargo/git/checkouts/radicle-link-009c17032bc5eda9/ce42a85/daemon/src/peer/run_state.rs:325
```

It would be great to be able to restore a lost project from the network.

**Comment by Kaihuang724** [comment]
Is this still relevant? This seems like a pretty important feature to implement quickly.

**Comment by rudolfs** [comment]
Yes, it's still relevant, but if I remember correctly, it wasn't straightforward to implement.
@geigerzaehler do you remember why we didn't do it?

**Comment by geigerzaehler** [comment]
We haven’t implemented this yet because it’s hard to determine the effort for this and will likely by high. I also think this is a quite unusual issue to run into. To lose your project data but retain your identity you need to mess with the librad storage. I think this problem arose when @rudolfs restored the storage from an old backup that did not have the project. I highly doubt that users will run into this. I would close this issue as wontfix.

**Comment by Kaihuang724** [comment]
Oh ok - if that's the case, I'll go ahead and close it. The way I was reading it - it seemed like if the user accidentally deleted his project folder as a maintainer, they wouldn't be able to clone their project back.
