### ISSUE TITLE
Implement new onboarding flow

### ISSUE THREAD

**Issue by Kaihuang724** [radicle-dev/radicle-upstream#2802]
We want to implement a more robust onboarding experience for our users in Upstream. The main demographics for the onboarding experience will be for both maintainers and collaborators on the project.

**User Stories**
* As a new user, when I open Upstream, I want the system to check whether I have the right Upstream CLI version installed (0.4.0) and that my PATH is set up correctly. If not, I want the system to either automate the CLI install or show me instructions on how to set it up correctly.
* As a new user, when I open Upstream, I want the system to check whether my Rad ID is correctly set up. If not, I want the system to show me instructions on how to set it up correctly.
* As a new user, when I open Upstream, I want the system to check whether my Git is correctly set up, and if I have a compatible version. If not, I want the system to show me instructions on how to set it up correctly.
* As a new user, when I'm done with the onboarding after opening Upstream, I want to be taken to the homepage so that I can either follow a project or create a new project.

**Notes**
* The instructions during onboarding should be written for both OSX and Linux systems.
* Designs are here: https://www.figma.com/file/Pj5gBf0TGRaWahkIVGJMpe/Onboarding-Process-Drafts?node-id=0%3A1

**Comment by efstajas** [comment]
Resolved [here](https://github.com/radicle-dev/radicle-upstream/commit/834a965a3fd6cfb5496ce89eaef0619fd57dc1c0) 

Notes:

> As a new user, when I open Upstream, I want the system to check whether I have the right Upstream CLI version installed (0.4.0) and that my PATH is set up correctly. If not, I want the system to either automate the CLI install or show me instructions on how to set it up correctly.

❌ The final implementation does **not** check for the Upstream CLI version because there are too many variables (custom shell setups, different startup files loaded by different shells, etc.) that make it hard to automatically detect a variable in PATH. We opted to make the user manually confirm that the Upstream CLI is installed in order to avoid false positives.

> As a new user, when I open Upstream, I want the system to check whether my Rad ID is correctly set up. If not, I want the system to show me instructions on how to set it up correctly.

✅ FYI, check the adjustment made to `development.md` in the commit for instructions on how to pass this check in development mode now that Upstream no longer creates identities on its own.

> As a new user, when I open Upstream, I want the system to check whether my Git is correctly set up, and if I have a compatible version. If not, I want the system to show me instructions on how to set it up correctly.

✅ This check is there, but may not work 100% in all situations depending on the user's environment. If we can auto-detect a version, it either automatically passes the check or displays a red warning if the version is too low. If it can't, it will ask the user to manually confirm.

> As a new user, when I'm done with the onboarding after opening Upstream, I want to be taken to the homepage so that I can either follow a project or create a new project.

✅ 

> The instructions during onboarding should be written for both OSX and Linux systems.

✅ Copy ended up being platform-agnostic.
