### ISSUE TITLE
`View in Browser` link for a project is broken

### ISSUE THREAD

**Issue by sebastinez** [radicle-dev/radicle-upstream#2822]
I tried to view a project in the browser through the `View in Browser` button and it redirect me to the web client but with `null` as seed. e.g. `https://app.radicle.network/seeds/null/rad:git:hnrkyacwc9quo148dhsng3q6743fqahrzyo3o`

<img width="1295" alt="Bildschirmfoto 2022-04-26 um 14 17 08" src="https://user-images.githubusercontent.com/7912302/165298125-02a393b8-aa85-4f10-8df8-2b640ba53395.png">

Not sure where you fetch the possible seeds, but wanted to give you a heads up

**Comment by rudolfs** [comment]
Thanks for documenting this.

Upstream iterates over all seeds to fetch every project's data, this happens every 10 seconds or so. Since we don't store the project <-> seed mapping in the monorepo, but in the Upstream kv store, Upstream only learns about that during the first sync. So there's a short time window where that mapping isn't set.

Perhaps a workaround would be to just not show the link until we fetch the project for the first time?
