### ISSUE TITLE
How should we communicate partially replicated data?

### ISSUE THREAD

**Issue by sarahscott** [radicle-dev/radicle-upstream#384]
e.g. when we can get data from the registry and we do not yet have the associated data from coco

cc: @radicle-dev/product

**Comment by cloudhead** [comment]
@juliendonck is working on this afaik.

Also note that we *do* (or should) have the coco URN for a project if we have the registry entry, since we're supposed to store that in the registry.

Also I wrote this doc recently, which is relevant: https://www.notion.so/monadic/Data-Availability-569c6ece189f452daa00670af3b362d5

**Comment by juliendonck** [comment]
I'd love to pair on this with you @sarahscott. Meaning that I'd like to see the different states and what kind of data we would have available so that I can properly guardrail them.

**Comment by sarahscott** [comment]
@juliendonck let's do it!

**Comment by juliendonck** [comment]
@cloudhead will join as well, will plan for next week. :)

**Comment by sarahscott** [comment]
Covered by #458 #459 #460
