### ISSUE TITLE
Connect app and proxy to different networks and nodes.

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-upstream#440]
As a developer I want to be able to work with the app on the ffnet as well as the devnet, a local node, and the registry emulator so that I can work with persistent data and test the app under realistic conditions. The mechanism for this should be properly documented.

In the future it should be possible to extend this mechanism to allow an app user to set the network/node host through a CLI flag when starting the app.

We will not implement the full network selector described in https://github.com/radicle-dev/radicle-upstream/issues/128.

**Comment by cloudhead** [comment]
Makes sense, although I'd expect as a developer to be able to pass these options via the CLI too, since editing the code isn't ideal.

I'm also realizing now that we are conflating two configurations (correct me if I'm wrong):
1. The application (proxy) wants to have the option to connect to a local node, vs. a remote node or network.
2. The registry node wants the option to connect to a chosen network (testnet/mainnet/ffnet).

Thinking about this more, I think the application shouldn't be concerned directly with ffnet/mainnet/etc (1). Rather, it should connect to some registry node somewhere and have the option to specify an address (2). And that node will be configured to join some network (testnet/mainnet).

**Comment by geigerzaehler** [comment]
What you said makes sense. I’ll need to look closer at this but what I’m imagining now for the implementation is to use some flag on the proxy that allows you to specify the node address. I’ll also add a shortcut (or documentation) for a ffnet host so that it is not necessary to run you own node.

**Comment by xla** [comment]
> Thinking about this more, I think the application shouldn't be concerned directly with ffnet/mainnet/etc (1). Rather, it should connect to some registry node somewhere and have the option to specify an address (2). And that node will be configured to join some network (testnet/mainnet).

I disagree with that direction while we should allow connection to a host/port pair we should also have simple ways of switching between our major networks, ideally through the settings (the interface exists). This will allow users to switch easily between the networks for different use-cases.

**Comment by geigerzaehler** [comment]
Thanks for the input @xla. I’d like to keep the discussion in this issue focused on the smaller scope of allowing developers to easily connect to a network and allowing users to connect to some node. For the larger issue we can discuss this in https://github.com/radicle-dev/radicle-upstream/issues/128.

**Comment by cloudhead** [comment]
> I disagree with that direction while we should allow connection to a host/port pair we should also have simple ways of switching between our major networks, ideally through the settings (the interface exists). This will allow users to switch easily between the networks for different use-cases.

I'm not sure what use-cases you're thinking about, but since the app will not always directly control the registry node it's connecting to, this seems impossible. Since this is a developer-only feature anyway, I don't see this as a problem either.
