### ISSUE TITLE
Error when using previously-used user handle

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/radicle-upstream#575]
The below was a bug. Now, if the session is completely obliterated :boom: it will work as desired. We would like, however, to better think about how the UX could be more friendly to the user.

### Original Bug
1. Start the app fresh, create an identity with `cloudhead` as the handle.
2. Go to settings, clear the session data.
3. Create a new identity with `cloudhead` again as the handle.
4. You should see an error: `Could not create identity: null`

In the logs, you see:
```
ERROR proxy::http::error > Rejection(EntityExists(RadUrn { id: Hash(Multihash([160, 228, 2, 32, 253, 128, 14, 198, 9, 1, 69, 86, 239, 232, 55, 170, 218, 106, 159, 168, 62, 97, 253, 86, 229, 14, 28, 34, 103, 55, 253, 132, 253, 163, 9, 247])), proto: Git, path: Path("") }))
```

**Comment by FintanH** [comment]
Right, that's because clearing the session data doesn't necessarily clear the monrepo data. Session is just some ephemeral state. The `rad/self` could make this more clear, where the user that was created becomes the defacto user for the session upon restart. We could add deleting the `rad/self` user too for deleting this user permanently.

**Comment by cloudhead** [comment]
I see, so the project listing isn't keyed by user `Urn` I guess?

**Comment by FintanH** [comment]
Nope, you would have to nuke the whole repo I believe. I suppose the assumption is that the monorepo is for this `PeerId` :thinking: This conversation is relevant I would say: https://github.com/radicle-dev/radicle-link/pull/198#issuecomment-648794985. The idea being, what happens when I want rotate my key and create a new monorepo.

**Comment by FintanH** [comment]
Chatted with @xla about this. We had some thoughts about this.

So to re-iterate, this issue is caused by:
* We created a `User` in the monorepo.
* The session holds this `User` as the identity.
* We clear the session.
* We are forced to create the `User` again and we pick the same `handle`. Also, note that the `SecretKey` is the same. So this means we have the same `RadUrn` in the monorepo.

The monorepo tells us that this `RadUrn` already exists and rightfully so.

I initially thought this could be remedied by fetching the `rad/self` from the monorepo and using that but that's not the most useful and hides away statefulness from the flow.

Instead, we should be thinking about how this flow can be augmented if we reach this case. Something that product would need to weigh in on.

Correct me on any of the details @xla if I was off on any of these points :ok_hand:

**Comment by rudolfs** [comment]
Workaround for now: `yarn nuke`.
https://github.com/radicle-dev/radicle-upstream/pull/626

**Comment by FintanH** [comment]
@xla is this "fixed" with latest and greatest obliteration code?

**Comment by xla** [comment]
Reopen if observed again.
