### ISSUE TITLE
Announcing Changes

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/radicle-upstream#602]
We cannot always guarantee that the proxy is running when code is being changed. This means that the monorepo can change while the proxy is _not_ running. The question then is: "How do we advertise the changes to any of the refs?"

There are currently two ideas for this:
* Periodically announce the HEADs of the refs
* Keep a snapshot of all `ref -> HEAD` pairs and only update when there are differences between the monorepo state and the snapshot.

**Comment by xla** [comment]
# CoCo::Announce

In order to announce local updates we need a way to know what has changed and
is worth communicating over the network so interested peers can fetch these
updates. For that a new coco module is proposed offering functionality:

* to diff and build up a list of noteworthy announcements
* datastructures to store and retrieve for caching the state used for diffing
* machinery that can be run in a background task to continuously do the diffing
  and announcing

## Flow

### Binary

The general flow will look like during proxy lifetime will look like:

* trigger `announcement routine` on startup
* spawn a watcher task
  * on a configurable interval run `announcement routine`

### Routine

The flow in the routine will look like:

* load latest cached state
* compute new state
  * list projects
  * get refs for project
  * get hashes/oid for refs
* compare differing hashes of refs
* announce updates
* update cache

## Interfaces

To illustrate what the surface is we like to cover have a trait:

``` rust
trait Announcer {
    fn announce(announcements: Vec<Announcement>) -> Result<(), Error>;
    fn diff(left: State, right: State) -> Vec<Announcement>;

    fn cache(state: State) -> Result<(), Error>;
    fn load() -> Result<State, Error>;
}
```

As we want to keep track of projects, their refs and the corresponding hashes,
the `State` could look like:

``` rust
type State = HashMap<RadUrm, HashMap<String, Oid>>;
```

The shape of an `Announcement` could look like:

``` rust
type Announcement = (RadUrn, Vec<Rev>);
```

**Comment by kim** [comment]
@xla There is a potential simplification: every `link` repo (ie. namespace) has a `refs/rad/signed_refs` ref, which contains a list of local refs + the tracked remotes (without any refs). The contents can be obtained via [`Storage::rad_signed_refs`]. Every time the repo is updated (ie. pushed to), a new commit is made on this branch.

So, the `State` above actually only needs to keep track of the `Oid` the `signed_refs` branch is pointing to. If it hasn't changed since the last announcement, do nothing, otherwise load the signed `Refs` for the `RadUrn`, and fire announcements for each local branch.

(_Note: technically, a peer would also gossip updates it receives for tracked peers, but I think we don't want that in this case)_
