### ISSUE TITLE
Clicking on a user on the Members page of an org should go to user's profile

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#745]
![image](https://user-images.githubusercontent.com/4406983/89177117-0b00e580-d58b-11ea-9316-55d098353ff4.png)

**Comment by MeBrei** [comment]
I don't think that this is planned in the first version of profiles. In #558 it is part of the features that should be hidden. 
Members of an org are registered users on the registry. The profile visitor view currently shows no data from the registry.

@cloudhead has maybe more thoughts on this. Could we still show the limited profile view for the member, if we have projects they are involved with locally?

**Comment by cloudhead** [comment]
I can't think of any problems with having this feature, given that we have profiles. Of course, we have to show the users as being registered in the profiles in that case, otherwise it will be confusing.

Another thing we need is a mapping between `user.registered_handle -> user.rad_urn`, since the profiles are based on the `rad_urn`.

**Comment by cloudhead** [comment]
I do think that we can have it on low-priority though, and implement all the rest for now.

**Comment by xla** [comment]
Registry functionality has been removed.
