### ISSUE TITLE
Invalid query results in panic and empty server reply

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-upstream#788]
An invalid query string for the `/tree` and `/blob` endpoints results in a panic of the handling task and immediately closes the connection without sending a reply. The expected behavior is for the server to reply with status code 400.

The cause for this behavior is the `http::with_qs` function. The problem does not seem easy to fix because we can’t really produce warp rejections with a payload on a 400 status code :(

**Comment by xla** [comment]
It's not that hard to make that work, we just need to return a proper error in that function instead of panicing outright. We have error infrastructure to convert our errors to custom respones:

https://github.com/radicle-dev/radicle-upstream/blob/a308cb0f0cb3a92019cb521ba6dfb7d61a381229/proxy/src/http/error.rs#L74-L136
