### ISSUE TITLE
Project request supervision

### ISSUE THREAD

**Issue by sarahscott** [radicle-dev/radicle-upstream#803]
The story here is that as a user I have heard about a super cool project via [insert favourite social network here] and I have a `RadUrn`. I ask my network if anyone knows about this thing. This request ripples through the network until someone responds. The response includes a PeerId & Address. I can use this information to contact that peer and clone the project to my Monorepo. That's the happy path. The sad path is that the network may take a while to respond, it may not respond at all (for some given time), or I may fail to connect a peer that I get back. To keep track of requests that are waiting and their stages of the progress we need some kind of Waiting Area. Please take a ticket and we'll call you up when your order is ready, thank you.

More formally, we can split up the feature into two separate constituents. The first is the concept of the `Request`. Using the project request as the driving example, we see it takes some input -- the `RadUrn`. Some requirements that we consider sane are that we should be able to:
* Cancel a request
* Timeout a request
* Limit the number of attempts

These requirements, in turn, give us states of the request that are given for _any_ type of a request, but a request may also have its own states. For example, the project request would also have:
* Found a peer to clone from
* The project has been cloned

As well as this, there's the initial state where a request has simply been created. The final state is defined by a satisfied request, so in our case when a project has been cloned.

The second constituent is a `Supervisor` that manages a set of `Request`s. This component knows how to give us back information about `Request`s and their states. It should be able to:
* List the requests that it knows about
* Prevent double requests from being in-flight -- i.e. making the same request twice in quick succession is the same as making one request
* Exponentially back off requests with the same input
* Provide an overview of a request and its metadata (state, last timestamp of progress, etc.)
* Lookup a request given an identifier
* Provide the state changes for a given identifier -- useful for notifications

@xla foresees an event-driven interface for polling the `Supervisor` as useful. That is the `Supervisor` would have a `next` method which gives back the caller the next available request to execute (whether it's in a created and ready to go state or a state where it failed due to timing out -- or the like -- and it needs to be re-requested).

Another useful requirement would be to persist the state of a `Supervisor` and its `Request`s, but I believe this might fall out from being able to request the overview of the `Supervisor` mentioned above.

**Comment by NunoAlexandre** [comment]
This looks sweet!

I have implemented something very similar, albeit the p2p backend, where I wrote this ~task~ download manager to manage the download of content (documents, videos, audio, zips, etc) from different backends from a mobile app. It granted the ability to peek at the progress of any download. It wasn't implemented as a `Queue` but rather as a `HashMap` as I needed to lookup the status of an arbitrary download having an item `Id`, i.e,  `let download: Option<Download> = manager.get(id)`. That can be done with a `Queue` but then it becomes a `O(n)` operation.

From a UI perspective, it would make sense to have a little popup section on the side that users could peek and be notified of changes to the status of these tasks. It would also be interesting to consider allowing the user himself specify the `peer_id` and `ip` to where they want to get a specific item from. That would be useful in cases where, say, they were told by a friend about that cool project that their friend already has, which would avoid potential several network trips to finding that item when the user already knows where to find it. Ideally, the network works so well and is so responsive that such feature is not necessary, but I'm just mentioning it in case it becomes a useful consideration :)

**Comment by xla** [comment]
Great write-up @FintanH. 

> * Prevent double requests from being in-flight -- i.e. making the same request twice in quick succession is the same as making one request

Wouldn't it be simpler to require that requests are unique? Two requests can't have the same project they want to get. If you will a uniquness constraint on the project urn.

> * Lookup a request given an identifier

Here we can be specific as we know the identifier, it is the project urn. Hopefully we prevent the implementation of some id scheme.

Don't want to get into bike-shedding, but the term `Supervisor` is a bit loaded as it implies task scheduling or in actor based system process supervision. When in essence we want a list like datastructure with some sugar to filter the current list of requests. Additionally it should know how to serialise itself given that we want to persist it.

Given that we can't be certain that we can clone from the peers we learn about, we should expand on how we gather a list of potential peers and keep track of the interactions with them. I'd imagine that we as much as we do rerequests we attempt multiple clones, working through the list of peers we learned about during the request phase. Maybe even grow the list of known peerrs past the request stage in case our clone attempts fail. While this expands the request state machine I think it's vital for request full-fillment.

**Comment by FintanH** [comment]
> Wouldn't it be simpler to require that requests are unique? Two requests can't have the same project they want to get. If you will a uniquness constraint on the project urn.

I think we're saying the same thing just in different ways :) 

> Don't want to get into bike-shedding, but the term Supervisor is a bit loaded as it implies task scheduling or in actor based system process supervision. When in essence we want a list like datastructure with some sugar to filter the current list of requests. Additionally it should know how to serialise itself given that we want to persist it.

I think this it leading to a question I have in my head: which constituent should know about things like timeouts? Should each request know about its own timeout, or does the **BLACK BOX** know about timeouts and run the requests using them? I'm drifting towards the **BLACK BOX** because then it can also keep around the state like "number of attempts".

> Given that we can't be certain that we can clone from the peers we learn about, we should expand on how we gather a list of potential peers and keep track of the interactions with them. I'd imagine that we as much as we do rerequests we attempt multiple clones, working through the list of peers we learned about during the request phase. Maybe even grow the list of known peerrs past the request stage in case our clone attempts fail. While this expands the request state machine I think it's vital for request full-fillment.

So is what you're saying that we might want to have separate requests for the "Who has this project"-request and the "I'm cloning from X"-request, which combined perform the "Who has this project and clone it from them"-request?
If not could you reword or expand on what you mean? :)

**Comment by xla** [comment]
> I think we're saying the same thing just in different ways :)

I don't think so, you are saying two request for the same project urn can't run at the same time. I'm saying two requests for the same project urn can't exist in the first place.

> I think this it leading to a question I have in my head: which constituent should know about things like timeouts? Should each request know about its own timeout, or does the **BLACK BOX** know about timeouts and run the requests using them? I'm drifting towards the **BLACK BOX** because then it can also keep around the state like "number of attempts".

A request should hold all data relevant for it's lifecycle and full-fillment. If we want to record the current number of attempts we should update the request itself. For a timeout we need the timestamp of the last attempt plus a configured duration so we can ask: `now - request.last_attempt_timestamp >= CONFIGURED_TIMEOUT_DURATION`. The reason the data should be encapsulated in the request is so that other components which want to surface the request state can use that, an example is that the user would want to cancel if they see a request being attempted N times already.

If you mean the "Supervisor" when talking about the **BLACK BOX** I don't think it should "run" anything at all. As I said above if it would be a fancy list with methods to get a specialised views on it, like the next request in line, and update the state of a certain request.

> So is what you're saying that we might want to have separate requests for the "Who has this project"-request and the "I'm cloning from X"-request, which combined perform the "Who has this project and clone it from them"-request?
> If not could you reword or expand on what you mean? :)

Sorry if my writing was ambiguous or hard to comprehend. What I was trying to say is, that if we have an ongoing request we should continue to record the peers we learn about that offer to full-fill that request, so that for the case where we start transition the request to cloning and that fails we have fallback peers to reattempt the cloning. To illustrate:

* issue `Request`
* observe `Have(Peer1)`
  * transition `Request` to `FoundPeer`
* observe `Have(Peer2)`
  * add `Peer2` to a list of known peers for `Request`
* start cloning from `Peer1`
* observe `Have(Peer3)`
  * add `Peer3` to list of known peers for `Request`
* cloneing from `Peer1` failed
* start cloning from `Peer2`
  * clone successful
  * transition `Request` to `Cloned`
