### ISSUE TITLE
sync on startup

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/radicle-upstream#852]
When our peer is offline then this implies we miss announcements that might have happened during this period. To ensure that our Monorepo is up to date we want to do a round of fetches on the `RadUrn`s + `PeerId`s we have in our Monorepo. We should only do this upon startup of the peer.

**Comment by xla** [comment]
As we looked into it a bit more in depth in a call, we see the possibility that the syncing is kicked off by gossiping a set of `Want`s for the projects the peer is tracking. Leaving this here for completeness sake.

**Comment by FintanH** [comment]
Wait, where/when did we say it was sending off `Want`s?

**Comment by xla** [comment]
In the replication call yesterday. The flow we hinted at was for the peer on startup to send wants for all its tracked projects. At least that's the part I remember, as we concluded it's so closely related to reacting to announements of `Have`s that we should tackle these together.

**Comment by FintanH** [comment]
I think that was said in passing. I need to figure out if that's possible/what we want (no pun intended).

**Comment by xla** [comment]
# Coco::Sync

To keep the local state as up-to-date as possible we want to introduce
routine(s) for syncs. Most notably when starting up, but potentially after long
periods of being offline. Syncing is synonymous with performing fetch
operations from connected peers for repos the local peer is tracking. For that
a new coco module is proposed offering functionality to:

* build the list of repos we want to sync
* run the fetch against a conencted peer
* machinery to react to peer connections

## Flow

We have two potential ways to address syncing, which are described below.

### Shotgun fetch

Here we fetch indiscriminately from a number of freshly connected peers.

* build up list of repos we want to sync
* listen to `N` amount of `ProtocolEvent::Connected` events and for each
  * iterate over the list of to-be-synced repos and for each
  * do a fetch from the newly connected peer
  * ignore error indicating the peer doesn't have the repo

#### Pros

* latency as we sync as soon as peers are available
* due to its naïve approach relatively simple to implement

#### Cons

* wasteful as we do a lot of blind operations
* might miss the peers which actually have updates for us

### One-time gossip

Here we announce a set of `Want`s for the list of projects we track and wait
for peers in the network to reply with `Have`s.

* build up list of repos we want to sync
* wait for `N` amount of `ProtocolEvent::Connected` events and for each
  * announce a `Want`
  * wait for the correspondening `Have`s to return
  * fetch the repo from the peer which the `Have` came from

#### Pros

* we use the gossip layer
* any fetch machinery we build to react to unsolicited announcements can be
  piggybacked on

#### Cons

* availiabilty is questionable, for
  * the right peers need to be connected to get the messages
  * the peers need to stay around until we received the `Have` and started
    fetching
* latency is likely way worth given that a lot of messages have to traverse
  before we start any actual fetch operation

### Repeated gossip

Here we announce a set of `Want`s periodically and only happen to do that at
startup as well.

* every `Duration`
  * build up list of repos we want to sync and for each
  * announce a `Want`
  * fetch repos from peers that sent `Have`s

#### Pros

* we use the gossip layer
* any fetch machinery we build to react to unsolicited announcements can be
  piggybacked on
* we have a high likelihood getting all available updates on the network
* we are not sensitive to specific lifecycle events like startup and
  reconnecting

#### Cons

* latency for the initial sync is likely worth that immediately fetching

_We should also consider a combination of the shotgun fetches with periodically
gossiping `Want`s to combine the positive properties of both._

**Comment by cloudhead** [comment]
Hmmm, I would think that some of this should be a protocol concern, ie. the logic of it should not be in the app. For example, it's quite inefficient to send a message for each thing you're looking for, eg. 100s of projects and for each peer. Ideally you'd say "here's what I have" to a connected peer, and you'd send a `Vec<(Urn, Head)>` of sorts, and they would send back the updates they have for those Urns.

Additionally, I'd imagine that the protocol will eventually keep track of which peers have which projects, and so it wouldn't shotgun all peers indiscriminatily.

I think we should be careful not to end up having all kinds of p2p logic inside upstream, as this won't be reusable, and upstream doesn't have the information to make the best decisions either.

**Comment by cloudhead** [comment]
Perhaps as an MVP though, the safest bet is to periodically ask N random peers about all your projects.. that way it works even if you're disconnected for a while (Repeated gossip), and you don't spam your entire peer set either. But yeah, I'd keep it very naive in upstream-land for now.

**Comment by FintanH** [comment]
I think shotgun can be simplified. We have a set **My Projects** and for each **Project** we have a set **Remotes ~= PeerIds**. So when we connect to a **PeerId**, we just do a filter for of **My Projects** _where_ **PeerId in Remotes**, if the resulting set is not empty only then do we issue a request to fetch from that peer.

**Comment by kim** [comment]
The thing is that we only know that we want `Urn`, not what `Head` is. So, every peer who has `Urn` will respond to a `Want`, and then we're not much better off than the shotgun approach, as most of those fetches are likely going to be no-ops.

I did conciously not include a way to exchange the full state between two peers, because allowing indefinite-length lists on the wire is an invitation to slowloris-type of attacks. It could work by exchanging bloomfilters or merkle-trees, but that needs more thought.

The protocol should indeed keep track of the (ambiently) discovered `(Urn, PeerId)` mapping (up to some bound), for exactly this purpose (low-connectivity peers), but that needs more thought as well.

So, given that the first peers to connect to are meant to be seed nodes, just trying to fetch everything from them seems like a good option for now. Note that QUIC employs some sophisticated flow-control mechanisms, but it could be that some rate-limiting on the application layer is still necessary.

**Comment by kim** [comment]
@FintanH You're right, actually

**Comment by kim** [comment]
@FintanH Although, you'll need to track the seed node (directly or indirectly) for this to have the desired effect.

**Comment by xla** [comment]
@cloudhead Thanks for raising your concerns in https://github.com/radicle-dev/radicle-upstream/issues/852#issuecomment-685730271. Those are all valid points and seem to be shared concerns when talking among the @radicle-dev/engineering. Unfortunately these require mid/long-term changes down to our dependency. We need to find a way to enable the use-ase for now. More thoughts inline.

> Hmmm, I would think that some of this should be a protocol concern, ie. the logic of it should not be in the app. For example, it's quite inefficient to send a message for each thing you're looking for, eg. 100s of projects and for each peer. Ideally you'd say "here's what I have" to a connected peer, and you'd send a `Vec<(Urn, Head)>` of sorts, and they would send back the updates they have for those Urns.

As @kim mentioned in person, this could be effectively addressed if we would be able to speak git version 2 and have [`ls-refs`](https://git-scm.com/docs/protocol-v2#_ls_refs).

> I think shotgun can be simplified. We have a set **My Projects** and for each **Project** we have a set **Remotes ~= PeerIds**. So when we connect to a **PeerId**, we just do a filter for of **My Projects** _where_ **PeerId in Remotes**, if the resulting set is not empty only then do we issue a request to fetch from that peer.

@FintanH @kim What if we never connect to the peers again, that happen to be in our remotes? Would we not miss any other updates for our projects?

> The thing is that we only know that we want `Urn`, not what `Head` is. So, every peer who has `Urn` will respond to a `Want`, and then we're not much better off than the shotgun approach, as most of those fetches are likely going to be no-ops.

@kim Wouldn't the `Have` include the `Head` which would help to decide if we need to fetch or not?

**Comment by kim** [comment]
> What if we never connect to the peers again, that happen to be in our remotes? Would we not miss any other updates for our projects?

Right, having supernodes (aka seeds) in your tracking graph is beneficial.

> Wouldn't the `Have` include the `Head` which would help to decide if we need to fetch or not?

No, because we only know the `Head` we already have -- but we're interested in later ones.

**Comment by xla** [comment]
> Right, having supernodes (aka seeds) in your tracking graph is beneficial.

Is it currently possible to explicitely track a peer, the seed node in here, without scoping it to a `RadUrn`?

**Comment by kim** [comment]
Is it currently possible to explicitely track a peer, the seed node in this
> case, without scoping it to a RadUrn?
>
> It is in fact required to name a peer id — think of it as `git remote add
xla URL`, where the URL is magically the same for every remote, instead of
having to be globally unique like https://github.com/xla/...
