### ISSUE TITLE
testnet for p2p networking

### ISSUE THREAD

**Issue by sarahscott** [radicle-dev/radicle-upstream#908]
As discussed in #866, we need a way to test interactions between peers in both `proxy` and `ui` integration tests.

**Comment by FintanH** [comment]
To shed some more light on this issue:

We have certain tests with the proxy that involve having peer interactions. Some examples of these are:
* Revision selector with multiple peers to select from
* Having tracked projects in your monorepo
* Coming Soon: asking the network for a peer

These types of integration tests are best simulated with two proxy's talking to each other since this will be the actuality of how they will interact.

**Comment by xla** [comment]
> * Coming Soon: asking the network for a peer

Do you mean asking for a project?

**Comment by FintanH** [comment]
Correct, thanks for catching :+1:

**Comment by xla** [comment]
TODOs to be tackeld in this context:

* https://github.com/radicle-dev/radicle-upstream/pull/896#discussion_r490850297
* https://github.com/radicle-dev/radicle-upstream/pull/896#discussion_r490851360

**Comment by rudolfs** [comment]
Superseded by https://github.com/radicle-dev/radicle-upstream/issues/1475.
