### ISSUE TITLE
Extend reset commands

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#960]
For QA we should have a single command that removes everything, so testing can be done from a clean slate.
Currently `radicle-upstream-0.0.14.AppImage --reset-state` only resets state.

Besides state, we should also remove:
  - configuration stored on disk in the XDG location
  - installed helper binaries from: `$HOME/.radicle`

I propose we add these to `package.json` scripts:
  - ~~`yarn reset:state` resets only the state~~ we already have this
  - `yarn reset:config` remove old config files
  - `yarn reset:helpers` remove everything in `$HOME/.radicle`
  - `yarn reset:everything` all of the above

Also part of this issue: amend the QA docs and replace the `--reset-state` switch with `--reset-everything` in `main.js`.

<details>
<summary>
Notes
</summary>

- created by electron:
```
~/Library/Application\ Support/radicle-upstream
```

- created by proxy:
```
~/.radicle
~/Library/Application\ Support/xyz.radicle.radicle
~/Library/Application\ Support/xyz.radicle.radicle-upstream
```

- created only when starting a packaged (production) app:
```
~/Library/Preferences/radicle-upstream.monadic.xyz.plist
~/Library/Saved\ Application\ State/radicle-upstream.monadic.xyz.savedState
```

- commands to manually reset everything on macOS manually
```
rm -rf ~/.radicle
rm -rf ~/Library/Application\ Support/radicle-upstream
rm -rf ~/Library/Application\ Support/xyz.radicle.radicle
rm -rf ~/Library/Application\ Support/xyz.radicle.radicle-upstream
rm -rf ~/Library/Preferences/radicle-upstream.monadic.xyz.plist
rm -rf ~/Library/Saved\ Application\ State/radicle-upstream.monadic.xyz.savedState
```
</details>

**Comment by rudolfs** [comment]
To simplify things, I was trying to get rid of the redundant `~/Library/Application\ Support/radicle-upstream` directory, by forcing electron to write data to `~/Library/Application\ Support/xyz.radicle.radicle-upstream/electron`. But it's not possible to prevent electron from creating the initial directory on startup. Giving up on that endeavour for now.

<details>
<summary>
My attempt to set a custom `userData` directory
</summary>

```diff
diff --git a/native/main.js b/native/main.js
index 74020749..81cba4d3 100644
--- a/native/main.js
+++ b/native/main.js
@@ -6,13 +6,32 @@ import {
   clipboard,
   shell,
 } from "electron";
-const { execFile } = require("child_process");
+import { execFile } from "child_process";
+import fs from "fs";
 import path from "path";
 import * as ipc from "./ipc.js";

 const isDev = process.env.NODE_ENV === "development";
 const proxyPath = path.join(__dirname, "../../proxy");

+console.log("APP DATA PATH: ", app.getPath("appData"));
+console.log("USER DATA PATH: ", app.getPath("userData"));
+
+const appDataPath = app.getPath("appData");
+
+const userDataPath = path.join(
+  appDataPath,
+  "xyz.radicle.radicle-upstream/electron"
+);
+
+if (!fs.existsSync(userDataPath)) {
+  console.log("CREATING NEW DIRECTORY: ", userDataPath);
+  fs.mkdirSync(userDataPath, { recursive: true });
+}
+
+console.log("USING NEW DIRECTORY: ", userDataPath);
+app.setPath("userData", userDataPath);
+
 // The default value of app.allowRendererProcessReuse is deprecated, it is
 // currently "false".  It will change to be "true" in Electron 9.  For more
 // information please check https://github.com/electron/electron/issues/18397
```
</details>

<details>
<summary>
An empty `radicle-upstream` still gets created, even though electron stuff lands in `xyz.radicle.radicle-upstream/electron`
</summary>

```
Library/Application Support » ls -la |grep radicle
drwx------    3 rudolfs  staff    96 Sep 25 17:56 radicle-upstream
drwxr-xr-x    5 rudolfs  staff   160 Sep 25 17:55 xyz.radicle.radicle
drwxr-xr-x    4 rudolfs  staff   128 Sep 25 17:56 xyz.radicle.radicle-upstream

Library/Application Support » tree radicle-upstream
radicle-upstream
└── Dictionaries

1 directory, 0 files
Library/Application Support » tree xyz.radicle.radicle
xyz.radicle.radicle
├── git
│   ├── HEAD
│   ├── config
│   ├── description
│   ├── hooks
│   │   └── README.sample
│   ├── info
│   │   └── exclude
│   ├── objects
│   │   ├── info
│   │   └── pack
│   └── refs
│       ├── heads
│       └── tags
├── git-includes
└── keys
    └── librad.key

11 directories, 6 files
Library/Application Support » tree xyz.radicle.radicle-upstream
xyz.radicle.radicle-upstream
├── electron
│   ├── Cache
│   │   ├── cc1fe2aa8b6e7242_0
│   │   ├── index
│   │   └── index-dir
│   │       └── the-real-index
│   ├── Code\ Cache
│   │   ├── js
│   │   │   ├── index
│   │   │   └── index-dir
│   │   │       └── the-real-index
│   │   └── wasm
│   │       ├── index
│   │       └── index-dir
│   │           └── the-real-index
│   ├── Cookies
│   ├── Cookies-journal
│   ├── Dictionaries
│   ├── GPUCache
│   │   ├── data_0
│   │   ├── data_1
│   │   ├── data_2
│   │   ├── data_3
│   │   └── index
│   ├── Local\ Storage
│   │   └── leveldb
│   │       ├── 000003.log
│   │       ├── CURRENT
│   │       ├── LOCK
│   │       ├── LOG
│   │       └── MANIFEST-000001
│   ├── Network\ Persistent\ State
│   ├── Preferences
│   └── blob_storage
│       └── 8a119710-253b-4176-966c-4985b5a37a8a
└── store
    ├── blobs
    ├── conf
    └── db

16 directories, 23 files
```
</details>

**Comment by kim** [comment]
As voiced elsewhere, I **do not** think this is a good approach. The way these destructive operations are baked into the shipped software makes it too easy to accidentally run them on a non-dev installation -- with potentially catastrophic consequences. Package managers / installers typically leave auxiliary files in place unless they were not modified after the installation, or explicitly told to remove them, for this reason.

It also doesn't serve the QA goals well -- after the initial release, **all** subsequent releases will have to take into account that **existing** configuration and state data needs to either continue to work, or some migration process is run.

If you insist that the actual filesystem paths matter (which is arguable), a better approach would be to instruct testers to install the package in a pristine environment -- on macOS, the "Guest" user gets its home directory wiped after logout. Similarly, Linux users can create a temporary user, or use docker or some other `chroot` environment.

For development purposes, we already have the possibility to place XDG_* data under an arbitrary root directory. Instead of a temporary location (as is created when starting the proxy with `--test`), we could also allow to pass any directory as a parameter on startup, which would incidentally unlock a multi-profile feature.

I'm not sure what to do about electron's state, or whether it matters that much. I think it should be the job of the distribution package / installer to remove that when the application is uninstalled.

**Comment by rudolfs** [comment]
Done in #944.
