### ISSUE TITLE
Don't block Stream

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/radicle-upstream#981]
As pointed out here: https://github.com/radicle-dev/radicle-upstream/pull/967#discussion_r497503768

**Comment by kim** [comment]
I didn't realise in the comment that the `RwLock*Guard`s lifetimes are constrained to the `RwLock`. This means that there is not really a way to store away the `read()` future for polling (at least not without considerable lifetime gymnastics). So there are two possible solutions:

1. Use an ordinary `std::sync::RwLock`. We are (incidentally) guaranteed that we're accessing the lock from different executor threads (because `peer::Running` spawns), so the worst thing that can happen is that we pile up tasks waiting for a read lock until we run out of threads. `try_read` (and potentially `try_write`) can be used to yield if the lock can't be acquired immediately.

2. Keep using `tokio::sync::RwLock`, but implement the streams as `async fn -> impl Stream`s, which are then boxed to be stored inside `peer:Subroutines`.

**Comment by xla** [comment]
Currently thinking along the lines of https://github.com/radicle-dev/radicle-upstream/pull/983#discussion_r498690899
